services:
  pgadmin4:
    image: dpage/pgadmin4:9.18.0
    init: true
    pull_policy: always
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      TZ: ${TZ:-Europe/Oslo}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin4/pgpass:/pgpass:ro
    depends_on:
      postgresql:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
