#!/usr/bin/env bash
#
# Regenerate `packages/dhis2w-client/src/dhis2w_client/generated/v{N}` for each
# DHIS2 version passed (default: v41 v42 v43 v44).
#
# For every version, spins up a fresh empty DHIS2 N via docker, waits for
# readiness, runs `d2w dev codegen generate` against it, and tears the stack
# down before moving on. Per-version dumps under `infra/v{N}/dump.sql.gz` are
# swapped out for 20-byte empty-gzip placeholders for the duration so DHIS2's
# Flyway migrations run cleanly on every version (loading the seeded e2e dump
# into a fresh stack would break).
#
# On exit — success, failure, or Ctrl+C — the script always restores the
# original dumps and brings the stack down, so there's no silent drift in
# the working tree.
#
# Usage:
#   infra/scripts/codegen_all_versions.sh            # default set
#   infra/scripts/codegen_all_versions.sh v42 v43    # subset
#
# Expect ~8-12 minutes per version (pull + boot + schema migrate + codegen
# + teardown). Pre-pull images with `make -C infra pull DHIS2_VERSION=vN`
# beforehand if you want to shave a few minutes off the first run.

set -euo pipefail

DEFAULT_VERSIONS=(v41 v42 v43 v44)
if [ "$#" -gt 0 ]; then
  VERSIONS=("$@")
else
  VERSIONS=("${DEFAULT_VERSIONS[@]}")
fi

INFRA_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$INFRA_DIR/.." && pwd)"

# Loading a seeded v42 dump into a fresh v41 stack would fail schema
# migrations; an empty placeholder lets DHIS2 bootstrap its own schema via
# Flyway on first start. The trap restores the committed dumps on exit.
# shellcheck source=_placeholder_dumps.sh
. "$INFRA_DIR/scripts/_placeholder_dumps.sh"
placeholder_dumps_install

FAILED=()
for v in "${VERSIONS[@]}"; do
  echo
  echo "============================================================"
  echo ">>> DHIS2 $v"
  echo "============================================================"

  if ! make -C "$INFRA_DIR" up-fresh DHIS2_VERSION="$v"; then
    echo "!!! failed to bring up DHIS2 $v (image missing from Docker Hub?)"
    FAILED+=("$v:up")
    continue
  fi

  if ! make -C "$INFRA_DIR" wait; then
    echo "!!! $v did not become ready in time"
    FAILED+=("$v:wait")
    make -C "$INFRA_DIR" down >/dev/null 2>&1 || true
    continue
  fi

  echo ">>> running codegen for $v"
  # `generate` emits the /api/schemas tree (schemas_manifest.json); `fetch-openapi`
  # captures the live /api/openapi/openapi.json verbatim; `oas-rebuild` then
  # re-emits the OAS tree + openapi_manifest.json from it, taking raw_version
  # from the just-written schemas_manifest. All three keep the schema and OAS
  # halves of the tree on the same pinned release.
  if (cd "$REPO_ROOT" && uv run d2w dev codegen generate \
        --url http://localhost:8080 --username admin --password district \
        && uv run d2w dev codegen fetch-openapi \
        --url http://localhost:8080 --username admin --password district \
        && uv run d2w dev codegen oas-rebuild --version "$v"); then
    echo ">>> done with codegen for $v"
  else
    echo "!!! codegen failed for $v"
    FAILED+=("$v:codegen")
  fi

  # Dump the Flyway-bootstrapped schema over the placeholder as a diagnostic
  # of what this image migrated to. The cleanup trap moves the committed seeded
  # dump back over it on exit, so the working tree never keeps this file.
  # Exclusions mirror build_e2e_dump.py: analytics_* / aggregated_* /
  # completeness_* / _* are regenerated by analytics-trigger on restore.
  pg_container=$(docker ps --format '{{.Names}}' | grep -iE 'postgresql|postgres' | head -1 || true)
  out_dir="$INFRA_DIR/$v"
  out_dump="$out_dir/dump.sql.gz"
  if [ -n "$pg_container" ]; then
    mkdir -p "$out_dir"
    echo ">>> dumping $v schema to $out_dump"
    if docker exec "$pg_container" pg_dump --no-owner --no-privileges --no-sync \
          --clean --if-exists \
          --exclude-table="analytics_*" --exclude-table="aggregated_*" \
          --exclude-table="completeness_*" --exclude-table="_*" \
          -U dhis -d dhis | gzip -9 > "$out_dump"; then
      size=$(wc -c < "$out_dump")
      echo "    wrote $out_dump ($size bytes)"
    else
      echo "!!! pg_dump failed for $v"
      FAILED+=("$v:dump")
      rm -f "$out_dump"
    fi
  else
    echo "!!! no postgres container found to dump $v"
    FAILED+=("$v:dump-missing-container")
  fi

  make -C "$INFRA_DIR" down >/dev/null 2>&1 || true
done

echo
echo "============================================================"
if [ "${#FAILED[@]}" -eq 0 ]; then
  echo ">>> All versions generated successfully: ${VERSIONS[*]}"
  exit 0
fi
echo ">>> Finished with failures: ${FAILED[*]}"
exit 1
